エラーハンドリング設定

diff --git a/.github/workflows/cron.yml b/.github/workflows/cron.yml
--- a/.github/workflows/cron.yml
+++ b/.github/workflows/cron.yml
@@ -12,15 +12,30 @@ jobs:
 
     steps:
       - name: Checkout code
+        id: error1
+        continue-on-error: true
         uses: actions/checkout@v2
         
       - name: Set up Python 3.8
         uses: actions/setup-python@v1
         with:
           python-version: 3.8
+        id: error2
+        continue-on-error: true
+        if: ${{ steps.error1.outcome == 'failure' }}
+        run: |
+          echo "Error handling1"
+          echo ${{ steps.error1.outcome }}
+          exit 1
 
       - name: Install dependencies
+        id: error3
+        continue-on-error: true
+        if: ${{ steps.error2.outcome == 'failure' }}
         run: |
+          echo "Error handling2"
+          echo ${{ steps.error2.outcome }}
+          exit 1
           python -m pip install --upgrade pip
           pip install simplejson
           pip install pandas
@@ -29,12 +44,23 @@ jobs:
           pip install line-bot-sdk
 
       - name: env
+        id: error4
+        continue-on-error: true
+        if: ${{ steps.error3.outcome == 'failure' }}
         env:
           OWM_PLACE_ID: ${{ secrets.OWM_PLACE_ID }}
           OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
           LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
           LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
+        run: |
+          echo "Error handling3"
+          echo ${{ steps.error3.outcome }}
+          exit 1    
 
       - name: Run script on push
+        if: ${{ steps.error4.outcome == 'failure' }}
         run: |
+          echo "Error handling4"
+          echo ${{ steps.error4.outcome }}
+          exit 1
           python3 index.py
